http:
  port: 8080

cors:
  allowed_origins: 'some.url.example, other.url.example'
  allowed_headers: 'Content-Type, X-Auth-Token, Authorization, X-CSRF-Token, API-Version, Verbose, Cache-Control, X-Requested-With'
  allowed_methods: 'POST, GET, OPTIONS, PUT, DELETE, PATCH'

rabbitmq:
  url: localhost
  port: 5672
  queue: foo
  virtualhost: '/'
  username: guest
  password: guest
  ssl: false
  verify_ssl: true

database:
  url: localhost
  port: 5432
  username: postgres
  password: postgres