apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: waspy-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: foo-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: waspy
        image: nhumrich/waspy-example
        env:
        - name: SOME_KEY
          value: myval
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ['sleep', '5']
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          
